export const metadata = {
  title: "Untap — Privacy Policy",
};

const localDataItems = [
  "App selections — which apps and categories you have chosen to restrict",
  "Per-app settings — open delay durations, session time limits, and hard lock preferences",
  "Usage data — daily screen time and open counts for restricted apps, stored locally for your reference",
  "Focus Time settings — schedule and preferences for Focus mode",
  "Notification preferences — your reminder schedule and enabled/disabled state",
];

const permissions = [
  {
    title: "Screen Time (Family Controls)",
    body: "Required to monitor app usage and apply shields/blocks to restricted apps. This uses Apple's FamilyControls, ManagedSettings, and DeviceActivity frameworks. The data accessed through these APIs stays on your device and is governed by Apple's privacy protections.",
  },
  {
    title: "Notifications",
    body: "Used to send local alerts when session time limits are reached and to provide break reminders. No push notification servers are involved.",
  },
];

export default function PrivacyPage() {
  return (
    <section className="px-6 pb-20 pt-32 sm:pb-28 sm:pt-36">
      <article className="mx-auto w-full max-w-3xl">
        <div className="text-center">
          <h1 className="text-balance text-3xl font-medium leading-[1.2] tracking-tight sm:text-4xl md:text-5xl">
            Privacy Policy
          </h1>
          <p className="mt-4 font-mono text-xs uppercase tracking-widest text-[var(--muted)]">
            Last updated: February 12, 2026
          </p>
        </div>

        <div className="mt-14 space-y-10 text-base leading-7 text-[var(--muted)] sm:text-lg">
          <section>
            <h2 className="text-2xl font-medium tracking-tight text-[var(--foreground)]">
              Introduction
            </h2>
            <p className="mt-3">
              Untap (&quot;we,&quot; &quot;our,&quot; or &quot;the App&quot;) is
              developed and operated by MBP Softwares. We are committed to
              protecting your privacy. This Privacy Policy explains what
              information the App accesses, how it is used, and what choices you
              have.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-medium tracking-tight text-[var(--foreground)]">
              Information We Do Not Collect
            </h2>
            <p className="mt-3">
              Untap does not collect, store, or transmit any personal data to
              external servers. We have no analytics, no tracking, and no
              advertising SDKs. We do not have access to your personal
              information, contacts, location, photos, or browsing history.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-medium tracking-tight text-[var(--foreground)]">
              Data Stored Locally on Your Device
            </h2>
            <p className="mt-3">
              All data generated by Untap is stored exclusively on your device
              using Apple&apos;s standard storage mechanisms (UserDefaults and
              App Groups). This includes:
            </p>
            <ul className="mt-4 list-disc space-y-2 pl-6">
              {localDataItems.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
            <p className="mt-4">
              This data never leaves your device. You can erase all stored data
              at any time using the &quot;Reset All Data&quot; option in the
              App&apos;s settings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-medium tracking-tight text-[var(--foreground)]">
              Permissions
            </h2>
            <p className="mt-3">Untap requests the following permissions:</p>
            <div className="mt-4 space-y-4">
              {permissions.map((permission) => (
                <p key={permission.title}>
                  <span className="font-medium text-[var(--foreground)]">
                    {permission.title}
                  </span>{" "}
                  — {permission.body}
                </p>
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-medium tracking-tight text-[var(--foreground)]">
              Third-Party Services
            </h2>
            <p className="mt-3">
              Untap uses the following third-party service:
            </p>
            <p className="mt-4">
              <span className="font-medium text-[var(--foreground)]">
                RevenueCat
              </span>{" "}
              — Used solely for managing in-app subscriptions and purchases.
              RevenueCat may process transaction data (such as purchase
              receipts) as required by Apple&apos;s App Store. Please refer to
              RevenueCat&apos;s Privacy Policy for details on how they handle
              data.
            </p>
            <p className="mt-4">
              We do not use any other third-party analytics, advertising, or
              tracking services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-medium tracking-tight text-[var(--foreground)]">
              Children&apos;s Privacy
            </h2>
            <p className="mt-3">
              Untap does not knowingly collect personal information from
              children under 13. Because the App stores all data locally and
              does not transmit data externally, no personal information of any
              user, including children, is collected by us.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-medium tracking-tight text-[var(--foreground)]">
              Data Security
            </h2>
            <p className="mt-3">
              Since all data remains on your device, it is protected by your
              device&apos;s built-in security measures, including device
              passcode, Face ID, or Touch ID. We do not have access to your data
              and cannot retrieve it.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-medium tracking-tight text-[var(--foreground)]">
              Changes to This Policy
            </h2>
            <p className="mt-3">
              We may update this Privacy Policy from time to time. Any changes
              will be reflected on this page with an updated &quot;Last
              updated&quot; date. Continued use of the App after changes
              constitutes acceptance of the revised policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-medium tracking-tight text-[var(--foreground)]">
              Contact Us
            </h2>
            <p className="mt-3">
              If you have any questions or concerns about this Privacy Policy,
              please contact us at:{" "}
              <a
                href="mailto:info.mbpsoftwares@gmail.com"
                className="font-medium text-[var(--foreground)] underline decoration-[var(--accent)] underline-offset-4"
              >
                info.mbpsoftwares@gmail.com
              </a>
            </p>
          </section>
        </div>
      </article>
    </section>
  );
}
